version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_CREATE_TOPICS: "request:1:1, response:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  eureka-server:
    build: ./eureka-server
    ports:
      - "8090:8090"
  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    restart: on-failure
    depends_on:
      - eureka-server
  zuul-service:
    build: ./zuul-service
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - eureka-server
      - config-server
  first-service:
    build: ./first-service
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - eureka-server
      - config-server
      - zookeeper
      - kafka
  second-service:
    build: ./second-service
    ports:
      - "8082:8082"
    restart: on-failure
    depends_on:
      - eureka-server
      - config-server
      - zookeeper
      - kafka
      - zuul-service